// SPDX-License-Identifier: Apache-2.0
/**
 * Content-script import-closure checks (WO-105).
 *
 * A content script's imports are fetched by the page. Every file in that
 * transitive closure has to be listed in web_accessible_resources, and those
 * rules must be scoped to the named content-script hosts only.
 */
import { dirname, join } from "node:path";

export const CONTENT_SCRIPT_HOSTS = Object.freeze([
  "*://www.youtube.com/*",
  "*://www.tiktok.com/*",
]);

export const PREPARE_CHROME = "npm run prepare:chrome";
export const PREPARE_FIREFOX = "npm run prepare:firefox";

/** Static import specifiers resolved against the extension root. */
export function importsOf(relPath, source) {
  const src = source.get(relPath) || "";
  const specs = [];
  const staticRe = /^\s*import\s[^;]*?from\s+["']([^"']+)["']/gm;
  const bareRe = /^\s*import\s+["']([^"']+)["']/gm;
  const dynRe = /\bimport\(\s*["']([^"']+)["']\s*\)/g;
  for (const re of [staticRe, bareRe, dynRe]) {
    let m;
    while ((m = re.exec(src))) specs.push(m[1]);
  }
  const from = dirname(relPath);
  return specs
    .filter((s) => s.startsWith("."))
    .map((s) => join(from, s).replace(/\\/g, "/"))
    .filter((p) => source.has(p));
}

/** Extension-root-relative paths named in runtime.getURL("...") calls. */
export function getURLTargets(relPath, source) {
  const src = source.get(relPath) || "";
  const out = [];
  const re = /getURL\(\s*["']([^"']+)["']\s*\)/g;
  let m;
  while ((m = re.exec(src))) {
    if (source.has(m[1])) out.push(m[1]);
  }
  return out;
}

export function importClosure(roots, source) {
  const seen = new Set();
  const stack = [...roots];
  while (stack.length) {
    const f = stack.pop();
    if (!f || seen.has(f)) continue;
    seen.add(f);
    for (const dep of importsOf(f, source)) stack.push(dep);
    for (const dep of getURLTargets(f, source)) stack.push(dep);
  }
  return seen;
}

export function contentScriptEntries(manifest) {
  return (manifest.content_scripts || []).flatMap((cs) => cs.js || []);
}

export function listedWebAccessible(manifest) {
  return new Set(
    (manifest.web_accessible_resources || []).flatMap((w) => w.resources || []),
  );
}

/**
 * Browser-fetched modules in the content-script closure that are not listed
 * as web-accessible. Injected content_scripts entries are exempt.
 */
export function missingWebAccessible(manifest, source) {
  const entries = contentScriptEntries(manifest);
  const listed = listedWebAccessible(manifest);
  const roots = [...entries, ...[...listed].filter((f) => f.endsWith(".js"))];
  const needed = [...importClosure(roots, source)].filter((f) => !entries.includes(f)).sort();
  return {
    entries,
    listed,
    needed,
    missing: needed.filter((f) => !listed.has(f)),
  };
}

function sortedUnique(list) {
  return [...new Set(list)].sort();
}

/**
 * WAR rules that publish any observer-graph JS module must be scoped to all
 * and only the named content-script hosts. A host wildcard is never allowed.
 */
export function webAccessibleHostErrors(manifest, requiredHosts = CONTENT_SCRIPT_HOSTS) {
  const want = sortedUnique(requiredHosts);
  const scriptHosts = sortedUnique(
    (manifest.content_scripts || []).flatMap((cs) => cs.matches || []),
  );
  const errors = [];
  if (scriptHosts.join("\n") !== want.join("\n")) {
    errors.push(
      `content_scripts.matches = [${scriptHosts.join(", ")}], want [${want.join(", ")}]`,
    );
  }
  for (const rule of manifest.web_accessible_resources || []) {
    const resources = rule.resources || [];
    if (!resources.some((r) => r.endsWith(".js"))) continue;
    const got = sortedUnique(rule.matches || []);
    if (got.some((m) => m === "*://*/*" || m === "<all_urls>")) {
      errors.push(`web_accessible_resources uses a host wildcard: ${got.join(", ")}`);
    }
    if (got.join("\n") !== want.join("\n")) {
      errors.push(
        `web_accessible_resources matches = [${got.join(", ")}], want [${want.join(", ")}]`,
      );
    }
  }
  return errors;
}

/**
 * Which authoritative template the generated bytes match, or null if neither.
 * Comparison is exact bytes. Chrome is checked first; the templates differ.
 */
export function generatedManifestFamily(generated, templates) {
  if (generated.equals(templates.chrome)) return "chrome";
  if (generated.equals(templates.firefox)) return "firefox";
  return null;
}

export function staleGeneratedManifestMessage() {
  return (
    "extension/manifest.json matches neither manifest.chrome.json nor " +
    `manifest.firefox.json. Run: ${PREPARE_CHROME} or ${PREPARE_FIREFOX}`
  );
}
