// SPDX-License-Identifier: Apache-2.0
/**
 * The extension's three-gram tokenizer must agree with the daemon's, exactly.
 *
 * The daemon sends an opaque `token_index` and never the token text, so the
 * interface reproduces the list locally to know which three-gram a bar belongs
 * to. Two implementations of one rule drift, and a drifted mapping would colour
 * the wrong three-gram with complete confidence — so the expected values here
 * are generated from `store.CharTokensForWord` rather than written by hand.
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  SHARD_K,
  splitWords,
  normalize,
  charTokensForWord,
  tokenColoringForWord,
} from "../extension/lib/tokens.js";

// Generated by running store.CharTokensForWord over each input.
const FROM_DAEMON = JSON.parse(
  `{
 "  ": [],
 "Solar-Eclipse!": [
  " ec",
  " so",
  "ar ",
  "cli",
  "ecl",
  "ips",
  "lar",
  "lip",
  "ola",
  "pse",
  "r e",
  "se ",
  "sol"
 ],
 "a": [
  " a "
 ],
 "ab": [
  " ab",
  "ab "
 ],
 "abc": [
  " ab",
  "abc",
  "bc "
 ],
 "eclipse": [
  " ec",
  "cli",
  "ecl",
  "ips",
  "lip",
  "pse",
  "se "
 ],
 "hello world": [
  " he",
  " wo",
  "ell",
  "hel",
  "ld ",
  "llo",
  "lo ",
  "o w",
  "orl",
  "rld",
  "wor"
 ],
 "portland": [
  " po",
  "and",
  "lan",
  "nd ",
  "ort",
  "por",
  "rtl",
  "tla"
 ]
}`,
);

describe("three-gram tokenizer agrees with the daemon", () => {
  it("uses the same k", () => {
    assert.equal(SHARD_K, 3);
  });

  it("produces the daemon's tokens for every case", () => {
    for (const [word, expected] of Object.entries(FROM_DAEMON)) {
      assert.deepEqual(charTokensForWord(word), expected, `tokens for ${JSON.stringify(word)}`);
    }
  });

  it("normalizes the way the daemon does", () => {
    assert.deepEqual(splitWords("Solar-Eclipse! 2026"), ["solar", "eclipse"]);
    assert.equal(normalize("Solar-Eclipse!"), " solar eclipse ");
    assert.equal(normalize("!!!"), "");
  });
});

describe("token colouring", () => {
  it("gives each three-gram exactly one character, left to right", () => {
    const { chars, tokenIndex } = tokenColoringForWord("abc");
    // " abc " → tokens " ab", "abc", "bc " (sorted), each starting one char along
    assert.equal(chars.join(""), " abc ");
    const owned = tokenIndex.filter((i) => i >= 0);
    assert.equal(owned.length, charTokensForWord("abc").length);
    assert.equal(new Set(owned).size, owned.length, "a token owns more than one character");
  });

  it("maps a character to the token that starts there", () => {
    const word = "eclipse";
    const sorted = charTokensForWord(word);
    const { chars, tokenIndex } = tokenColoringForWord(word);
    for (let i = 0; i < chars.length; i++) {
      if (tokenIndex[i] < 0) continue;
      const here = chars.slice(i, i + SHARD_K).join("");
      assert.equal(sorted[tokenIndex[i]], here, `character ${i} of ${word}`);
    }
  });

  it("colours nothing for a word with no letters", () => {
    const { chars, tokenIndex } = tokenColoringForWord("!!!");
    assert.deepEqual(chars, []);
    assert.deepEqual(tokenIndex, []);
  });
});
